version: "3"
services:
  our-class-bank:
    image: our-class-bank-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
