springdoc:
  swagger-ui:
    tagsSorter: alpha
    path: /swagger-ui.html

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
