### 권한 검증이 필요하지 않은 api
GET {{host}}/api/v1/test/auth/null

> {%
    client.test("200", function () {
        client.assert(response.status === 200);
    });
%}


### ROLE=USER 권한이 필요한 api
# @no-cookie-jar
GET {{host}}/api/v1/test/auth/user

> {%
    client.test("권한 없음", function () {
        client.assert(response.status === 403);
    });
%}


### ROLE=banker 권한이 필요한 api
GET {{host}}/api/v1/test/auth/banker

> {%
    client.test("권한 없음", function () {
        client.assert(response.status === 403);
    });
%}


### 1. 회원 가입
# @no-cookie-jar
< {%
    request.variables.set("loginId", "choi123")
    request.variables.set("password", "1234")
    request.variables.set("name", "C병현")
    request.variables.set("role", "ROLE_USER")
%}
POST {{host}}/api/v1/user/signup
Content-Type: application/json

{
    "loginId": "{{loginId}}",
    "password": "{{password}}",
    "name": "{{name}}",
    "roles": ["{{role}}"]
}

> {%
    client.test(" 200", function () {
        client.assert(response.status === 200, response.status);
    });

    client.global.set("loginId", "choi123")
    client.global.set("password", "1234")
    client.global.set("name", "C병현")
    client.global.set("role", "ROLE_USER")
%}

### 2. 회원 로그인
POST {{host}}/api/v1/user/signin
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}

> {%
    client.test(" 200", function () {
        client.assert(response.status === 200, response.status);
    });
%}
