###
< {%
    client.global.set("testName", "banker 회원 로그인 api")

    client.global.set("bankerUsername", "banker001")
    client.global.set("bankerPassword", "1234")

    request.variables.set("bankerUsername", client.global.get("bankerUsername"))
    request.variables.set("bankerPassword", client.global.get("bankerPassword"))
%}
POST {{host}}/api/v1/auth/signin
Content-Type: application/json

{
  "username": "{{bankerUsername}}",
  "password": "{{bankerPassword}}"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200, response.status);
    });

    client.global.set("bankerToken", response.body["accessToken"])
%}

###
< {%
    client.global.set("testName", "내 계좌 목록 api")
%}
GET {{host}}/api/v1/my/account
Authorization: Bearer {{bankerToken}}
Content-Type: application/json

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200, response.status);
    });
%}

###
< {%
    client.global.set("testName", "같은 반 회원 조회 api")
%}
GET {{host}}/api/v1/user/same-class
Authorization: Bearer {{bankerToken}}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200);
    });

    client.global.set("pocketmoneyAccountNo", response.body[0]["pocketmoneyAccountNo"])
    client.global.set("studentUsername", response.body[0]["username"])
%}


###
< {%
    client.global.set("testName", "입금 api - accountNo=" + client.global.get("pocketmoneyAccountNo") + ", type=INCOME_SALARY, amount=9000, description=1월 월급")
%}
POST {{host}}/api/v1/account/pocketmoney/deposit
Authorization: Bearer {{bankerToken}}
Content-Type: application/json

{
  "accountNo": "{{pocketmoneyAccountNo}}",
  "type": "INCOME_SALARY",
  "amount": 9000,
  "description": "1월 월급"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200);
    });
%}

###
< {%
    client.global.set("testName", "입금 api - accountNo=" + client.global.get("pocketmoneyAccountNo") + ", type=INCOME_SALARY, amount=3500, description=교내 미술대회 입상")
%}
POST {{host}}/api/v1/account/pocketmoney/deposit
Authorization: Bearer {{bankerToken}}
Content-Type: application/json

{
  "accountNo": "{{pocketmoneyAccountNo}}",
  "type": "INCOME_PRIZE_MONEY",
  "amount": 3500,
  "description": "교내 미술대회 입상"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200);
    });
%}

###
< {%
    client.global.set("testName", "출금 api - accountNo=" + client.global.get("pocketmoneyAccountNo") + ", type=EXPENSE_FINE, amount=4000, description=지각")
%}
POST {{host}}/api/v1/account/pocketmoney/deposit
Authorization: Bearer {{bankerToken}}
Content-Type: application/json

{
  "accountNo": "{{pocketmoneyAccountNo}}",
  "type": "EXPENSE_FINE",
  "amount": 4000,
  "description": "지각"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200);
    });
%}

###
< {%
    client.global.set("testName", "출금 api - accountNo=" + client.global.get("pocketmoneyAccountNo") + ", type=EXPENSE_ETC, amount=2700, description=미화용품 구매")
%}
POST {{host}}/api/v1/account/pocketmoney/deposit
Authorization: Bearer {{bankerToken}}
Content-Type: application/json

{
  "accountNo": "{{pocketmoneyAccountNo}}",
  "type": "EXPENSE_ETC",
  "amount": 2700,
  "description": "미화용품 구매"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200);
    });
%}

###
< {%
    client.global.set("testName", "BANKER 가 수행한 입출금 기록 조회 api by banker")

    request.variables.set("fromAt", "2020-01-01T00:00:00.000")
    request.variables.set("toAt", "2999-01-31T23:59:59.999")
%}
GET {{host}}/api/v1/account/pocketmoney/history?fromAt={{fromAt}}&toAt={{toAt}}
Content-Type: application/json
Authorization: Bearer {{bankerToken}}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200, response.status);
    });
%}

###
< {%
    client.global.set("testName", "student 회원 로그인 api")

    client.global.set("studentUsername", client.global.get("studentUsername"))
    client.global.set("studentPassword", "1234")

    request.variables.set("studentUsername", client.global.get("studentUsername"))
    request.variables.set("studentPassword", client.global.get("studentPassword"))
%}
POST {{host}}/api/v1/auth/signin
Content-Type: application/json

{
  "username": "{{studentUsername}}",
  "password": "{{studentPassword}}"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200, response.status);
    });

    client.global.set("studentToken", response.body["accessToken"])
%}

###
< {%
    client.global.set("testName", "내 입출금 기록 조회 api")

    request.variables.set("fromAt", "2020-01-01T00:00:00.000")
    request.variables.set("toAt", "2999-01-31T23:59:59.999")
%}
GET {{host}}/api/v1/my/account/history/{{pocketmoneyAccountNo}}?fromAt={{fromAt}}&toAt={{toAt}}
Content-Type: application/json
Authorization: Bearer {{studentToken}}

{
  "username": "{{studentUsername}}",
  "password": "{{studentPassword}}"
}

> {%
    client.test(client.global.get("testName") + " - 200", function () {
        client.assert(response.status === 200, response.status);
    });
%}
